title: RevolutionUC Hackathon - Spring 2019
description: "Midwest Student Hackathon held at the University of Cincinnati"
url: "http://revolutionuc.com"

sass:
  sass_dir: _scss
  style: :compressed

# items to exclude from the build
exclude: ["vendor", "README.md", "Rakefile", "Gemfile", "Gemfile.lock", "LICENSE"]

plugins:
  - jekyll-sitemap
